run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning
  gosec:
    excludes:
      - G104 # Unhandled errors (we handle them explicitly where needed)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
